//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;

[assembly: System.Reflection.AssemblyCompanyAttribute("Code Shayk")]
[assembly: System.Reflection.AssemblyConfigurationAttribute("Release")]
[assembly: System.Reflection.AssemblyCopyrightAttribute("2024")]
[assembly: System.Reflection.AssemblyDescriptionAttribute(".Net Library to implement feature toggles.")]
[assembly: System.Reflection.AssemblyFileVersionAttribute("4.0.0.0")]
[assembly: System.Reflection.AssemblyInformationalVersionAttribute("4.0.0")]
[assembly: System.Reflection.AssemblyProductAttribute("FeatureOne")]
[assembly: System.Reflection.AssemblyTitleAttribute("FeatureOne")]
[assembly: System.Reflection.AssemblyVersionAttribute("4.0.0.0")]
[assembly: System.Reflection.AssemblyMetadataAttribute("RepositoryUrl", "https://github.com/TechNinjaLabs/FeatureOne")]

// Generated by the MSBuild WriteCodeFragment class.

